/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class server_Hello */

#ifndef _Included_server_Hello
#define _Included_server_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     server_Hello
 * Method:    sayHi
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_server_Hello_sayHi
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     server_Hello
 * Method:    exportKeyingMaterian
 * Signature: (Ljavax/net/ssl/SSLSocket;[BJ[CJ[CJI)V
 */
JNIEXPORT void JNICALL Java_server_Hello_exportKeyingMaterian
  (JNIEnv *, jobject, jobject, jbyteArray, jlong, jcharArray, jlong, jcharArray, jlong, jint);

/*
 * Class:     server_Hello
 * Method:    GetSslVersion
 * Signature: (Ljavax/net/ssl/SSLSocket;)V
 */
JNIEXPORT void JNICALL Java_server_Hello_GetSslVersion
  (JNIEnv *, jobject, jobject);

/*
 * Class:     server_Hello
 * Method:    EVP_MD_CTX_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_server_Hello_EVP_1MD_1CTX_1create
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
